language: node_js

sudo: required

node_js:
  - "12.19.0"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g ganache-cli truffle
  - npm install -g @openzeppelin/contracts

install:
  - npm install 

before_script: chmod +x build.sh

script: ./build.sh
